services:
  postgres:
    image: postgres:16-alpine
    # image: pgvector/pgvector:pg17
    container_name: storyboard-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storyboard
    ports:
      - '5432:5432'
    volumes:
      - ~/docker/postgres/storyboard-postgres:/var/lib/postgresql/data # Mount a persistent volume for data
